name: Start

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: ["lint", "test"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.14.0"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run ${{ matrix.task }}
        run: npm run ${{ matrix.task }}
